
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /tokio

spring:
  application:
    name: scheduling-api
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

  jmx:
    enabled: false
  datasource:
    url: jdbc:h2:mem:technical_test;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
